/**
 * Дополнительные профили /guest/friend/:slug для комментаторов демо.
 * Имя в профиле должно совпадать с полем who в комментарии.
 */

function fp(name, handle, bio, bannerClass = 'guest-cbanner--void', photos = 0, posts = []) {
  return { name, handle, status: 'в сети', bio, bannerClass, photos, posts };
}

const ARCH = Object.fromEntries(
  Array.from({ length: 21 }, (_, i) => {
    const n = i + 4;
    return [
      `arch${n}`,
      {
        name: `Архив_${n}`,
        handle: `@arch_${n}`,
        status: 'архив треда',
        bio: 'Комментатор старого поста ленты Tiver.',
        bannerClass: 'guest-cbanner--void',
        photos: 0,
        posts: [],
      },
    ];
  }),
);

export const GUEST_COMMENT_EXTRA_FRIENDS = {
  ...ARCH,
  tim: fp('Тим', '@tim_bits', 'Про букву T, логотипы и локальные культы.', 'guest-cbanner--cross', 1),
  sergey: fp('Сергей', '@sergey_dash', 'Виджеты, дашборды и честный сайдбар.', 'guest-cbanner--grid', 2),
  masha: fp('Маша', '@masha_ui', 'Пиксель, кнопки и «ещё один клик».', 'guest-cbanner--dots', 4),
  artem: fp('Артём', '@artem_guest', 'Гостевой режим как фича, не как баг.', 'guest-cbanner--hatch', 1),
  kira: fp('Кира', '@kira_67', 'Про ориентиры качества и мемы с цифрами.', 'guest-cbanner--brick', 2),
  ira: fp('Ира', '@ira_iso', 'Плёнка, ISO и честные восьмибитные отговорки.', 'guest-cbanner--brick', 6),
  kostya: fp('Костя', '@kostya_light', 'Лайтрум, серии и «отпишусь в треде».', 'guest-cbanner--cross', 3),
  vadim: fp('Вадим', '@vadim_pixel', 'Chrome.css, Pixel и проверки на железе.', 'guest-cbanner--grid', 2),
  sonya: fp('Соня', '@sonya_archive', 'Архив 2021 и спокойствие в репозитории.', 'guest-cbanner--void', 1),
  nikita_feed: fp('Никита', '@nikita_screen', 'Скрин «в голове» и экономия трафика.', 'guest-cbanner--dots', 5),
  liza: fp('Лиза', '@liza_chrome', 'Кнопка 2026 и легенды гостевой ленты.', 'guest-cbanner--hatch', 2),
  pasha: fp('Паша', '@pasha_honest', 'Честность в описании бага — база.', 'guest-cbanner--brick', 1),
  moderator_feed: fp('Модератор', '@mod_feed', 'Следит за тоном треда и за буквой T.', 'guest-cbanner--cross', 0),
  guest7: fp('Гость_7', '@guest_ring_7', 'Локальные мемы и чай в комментариях.', 'guest-cbanner--void', 0),
  guest8: fp('Гость_8', '@guest_ring_8', 'Согласен с большинством, кроме понедельника.', 'guest-cbanner--void', 0),
  guest9: fp('Гость_9', '@guest_ring_9', 'Тесты на телефоне, не на духовке.', 'guest-cbanner--void', 0),
  guest10: fp('Гость_10', '@guest_ring_10', 'CSS 2021 пусть отдыхает.', 'guest-cbanner--void', 0),
  guest11: fp('Гость_11', '@guest_ring_11', 'Tiver с T — как твит с твитом.', 'guest-cbanner--void', 0),
  guest12: fp('Гость_12', '@guest_ring_12', 'Лента живая, пока есть кофе.', 'guest-cbanner--void', 0),
  designer_u: fp('Дизайнер', '@designer_pixel', 'Пиксель только в госте — спорит с продактом.', 'guest-cbanner--hatch', 3),
  product_u: fp('Продакт', '@product_notion', 'Опросы в Notion, сердца в ленте.', 'guest-cbanner--brick', 2),
  vika: fp('Вика', '@vika_team', '67% команды за «только в госте».', 'guest-cbanner--dots', 1),
  semyon: fp('Семён', '@semyon_font', 'T в шрифте — ок, главное не Comic Sans.', 'guest-cbanner--grid', 0),
  anya: fp('Аня', '@anya_min', 'Минимализм: мало кнопок, много драмы.', 'guest-cbanner--void', 1),
  dima: fp('Дима', '@dima_radius', 'Локальный мем: «ещё один радиус — и я сплю».', 'guest-cbanner--cross', 2),
  yura: fp('Юра', '@yura_pixel_vote', 'Голосует за пиксель в госте единогласно.', 'guest-cbanner--hatch', 0),
  roma: fp('Рома', '@roma_lint', 'Линтер как психотерапевт: сначала бесит, потом не отпускает.', 'guest-cbanner--cross', 4),
  yulya: fp('Юля', '@yulya_privacy', 'Приватность в закладки, без крика.', 'guest-cbanner--dots', 2),
  digest_yul: fp('Дайджест', '@digest_bot', 'Блок про cookies — там тоже драма.', 'guest-cbanner--grid', 0),
  max_d: fp('Макс', '@max_links', '67 ссылок было бы идеально, хватит и 12.', 'guest-cbanner--brick', 1),
  nika: fp('Ника', '@nika_trust', 'T — trust, если по-английски.', 'guest-cbanner--hatch', 2),
  oleg: fp('Олег', '@oleg_legacy', 'С тех пор столько всего — а лента всё ещё наша.', 'guest-cbanner--grid', 3),
  lena: fp('Лена', '@lena_css21', 'Архив CSS помним. Ностальгия по кнопке 2021.', 'guest-cbanner--hatch', 5),
  tiverdev: fp('Tiver Dev', '@tiver_dev', 'Спасибо, что читаете с самого начала.', 'guest-cbanner--dots', 0),
  anna_k: fp('Анна К.', '@anna_k_erp', 'Сверки, чай и спокойствие в конце месяца.', 'guest-cbanner--hatch', 8),
  petr: fp('Пётр', '@petr_regs', 'Регламенты и закрытие периода без драмы.', 'guest-cbanner--brick', 4),
  oksana: fp('Оксана', '@oksana_check', 'Чек-листы и закрепы вместо хаоса.', 'guest-cbanner--dots', 6),
  zup_mascot: fp('ЗУП-бот', '@zup_mascot', 'Напоминает про cf/cu и про кофе.', 'guest-cbanner--grid', 0),
  raccoon_1c: fp('1С-енот', '@raccoon_1c', 'Табель, T и отчётность с иронией.', 'guest-cbanner--cross', 2),
  mod_comm: fp('Модератор', '@mod_comm_erp', 'Контур ожиданий бизнеса и порядок в треде.', 'guest-cbanner--grid', 1),
  oleg_fin: fp('Олег', '@oleg_fin_lines', 'Скрины, пятые строки и внимание к деталям.', 'guest-cbanner--cross', 3),
  buh_zup: fp('Бух', '@buh_zup', 'Дубли кадровых, ЗУП и «типовая не виновата».', 'guest-cbanner--brick', 7),
  skd_expert: fp('СКД-guru', '@skd_guru', 'Запятые в выражениях и отчёты без сюрпризов.', 'guest-cbanner--dots', 9),
  sasha_rel: fp('Саша', '@sasha_release', 'Обновления по пятницам и «держим крестики».', 'guest-cbanner--hatch', 4),
  mark_ext: fp('Марк', '@mark_zup_ext', 'Расширения только через поддержку.', 'guest-cbanner--cross', 2),
  guest_erp: fp('Гость ERP', '@guest_erp', 'Локальный мем: «ещё один обмен и я домой».', 'guest-cbanner--void', 0),
  devops_x: fp('Девопс', '@devops_copy', 'Копии, cf и честные пайплайны.', 'guest-cbanner--hatch', 5),
  accountant_n: fp('Бухгалтер', '@accountant_bank', 'Банк, таймауты и вопросы «это они или мы».', 'guest-cbanner--grid', 6),
  release_mgr: fp('Релиз-менеджер', '@release_mgr', 'Очереди ровные, как СКД без запятых.', 'guest-cbanner--dots', 3),
  onec_joker: fp('1С-шут', '@onec_joker', 'Простой и честный юмор про 67 минут простоя.', 'guest-cbanner--brick', 1),
  newbie_z: fp('Новичок', '@newbie_restart', 'Кэш, перезапуск и самоирония.', 'guest-cbanner--void', 0),
  tech_line: fp('Техподдержка', '@tech_line_1c', 'T — терпение. И честные инструкции.', 'guest-cbanner--cross', 1),
  veteran_u: fp('Старожил', '@veteran_u', 'Перезапуск лечит 80% — проверено годами.', 'guest-cbanner--grid', 11),
  it_zup: fp('ИТ', '@it_zup_roll', 'Копия прошла, бой молится.', 'guest-cbanner--grid', 4),
  kadry_hr: fp('Кадры', '@kadry_hr', 'Дубль кадрового как жанр ужаса, а это четверг.', 'guest-cbanner--dots', 5),
  dev_1c: fp('Разработчик', '@dev_1c_ext', 'Откат, кофе, потом снова героизм.', 'guest-cbanner--hatch', 8),
  skd_watch: fp('СКД-наблюдатель', '@skd_watch', 'Отчёты, cf и честные 67.', 'guest-cbanner--void', 4),
  tester_qa: fp('Тест', '@tester_qa_copy', 'Копия за 10 минут, бой — для героев.', 'guest-cbanner--brick', 3),
  reader_a: fp('Читатель', '@reader_scroll', 'Лонгриды без «ещё 10 минут».', 'guest-cbanner--dots', 2),
  editor_scroll: fp('Редакция', '@editor_scroll', 'Оглавление внизу — проверьте.', 'guest-cbanner--void', 1),
  front_lead: fp('Фронт', '@front_lead', 'Зелёные пайплайны и подозрение к удаче.', 'guest-cbanner--brick', 3),
  devops_e: fp('DevOps_енот', '@devops_raccoon', 'Рука на «откат» и честный CI.', 'guest-cbanner--hatch', 6),
  qa_e: fp('QA', '@qa_e', 'Happy path и записи в тест-план.', 'guest-cbanner--grid', 4),
  grid_enj: fp('Grid enjoyer', '@grid_enj', 'display: drama; и честная сетка.', 'guest-cbanner--cross', 2),
  flex_enj: fp('Flex enjoyer', '@flex_enj', 'justify-content: peace;', 'guest-cbanner--dots', 3),
  subgrid_c: fp('Subgrid cult', '@subgrid_c', 'align-self: therapy;', 'guest-cbanner--brick', 1),
  enjoy67: fp('67 enjoyer', '@enjoy67', 'width: 67%; хахахаха', 'guest-cbanner--grid', 0),
  t_fan: fp('T-фан', '@t_fan_css', 'letter-spacing: Tiver;', 'guest-cbanner--hatch', 1),
  kaskad: fp('Каскад', '@kaskad_imp', '!important — только по пятницам.', 'guest-cbanner--void', 2),
  flexer2: fp('Флексер', '@flexer2', 'gap: emotion; уже в проде души.', 'guest-cbanner--cross', 1),
  memolog: fp('Мемолог', '@memolog', 'Ещё один медиазапрос — и в Зал славы.', 'guest-cbanner--dots', 2),
  typograph_d: fp('Типограф', '@typograph_d', '4pt, иначе baseline плачет.', 'guest-cbanner--hatch', 7),
  product_ui: fp('Продукт', '@product_ui', 'Главное — чтобы везде одинаково.', 'guest-cbanner--void', 2),
  pod_listener: fp('Слушатель', '@pod_listener', 'Таймкоды на слабые места — огонь.', 'guest-cbanner--grid', 1),
  mic_host: fp('Микрофон', '@mic_host', 'Честный рефактор в следующем выпуске.', 'guest-cbanner--dots', 0),
  listener67: fp('67-й слушатель', '@listener67', 'Выпуск как бэкап — нужен всегда.', 'guest-cbanner--hatch', 2),
  t_pod: fp('T-подкаст', '@t_pod', 'Буква T в названии — не спорим.', 'guest-cbanner--cross', 1),
  anna_feed: fp('Анна', '@anna_feed_1c', 'Жёлтая тема и неожиданный уют.', 'guest-cbanner--hatch', 3),
  petr_feed: fp('Пётр', '@petr_feed_bk', 'Бэкап сделал — можно жить.', 'guest-cbanner--brick', 4),
  guest_you_feed: fp('Вы (гость)', '@guest_you_feed', 'Локально всё честно подсвечено.', 'guest-cbanner--grid', 0),
  zup_bot_feed: fp('ЗУП-бот', '@zup_bot_feed', 'cf/cu в пятницу — только с копией.', 'guest-cbanner--grid', 0),
  skd_guru_feed: fp('СКД-guru', '@skd_guru_feed', '67-я запятая в отчёте — традиция.', 'guest-cbanner--dots', 5),
  buh_feed: fp('Бух', '@buh_feed', 'Обновление: чай, потом кнопки.', 'guest-cbanner--cross', 6),
  oleg_feed: fp('Олег', '@oleg_feed_forms', 'Версии форм и честный перезапуск.', 'guest-cbanner--void', 2),
  mod_feed_1c: fp('Модератор', '@mod_feed_1c', 'T в названии отчёта — табель.', 'guest-cbanner--hatch', 1),
  kadry_feed: fp('Кадры', '@kadry_feed', 'ЗУП после обмена — как понедельник.', 'guest-cbanner--brick', 4),
  ilya_feed: fp('Илья', '@ilya_feed', 'Регламент и «ещё один домой».', 'guest-cbanner--grid', 3),
  lin_feed: fp('Лин', '@lin_feed', 'Расширение без поддержки — как спагетти без вилки.', 'guest-cbanner--dots', 5),
  sasha_feed: fp('Саша', '@sasha_feed', 'Типовая не виновата — проверьте обмен.', 'guest-cbanner--cross', 4),
  participant_demo: fp('Участник', '@participant_demo', 'Закладки и спасибо за пост.', 'guest-cbanner--dots', 1),
  guest_demo: fp('Гость', '@guest_demo_q', 'Интересно, как будет после входа.', 'guest-cbanner--void', 0),
  mod_demo: fp('Модератор', '@mod_demo', 'Макет: ответы и счётчики локальные.', 'guest-cbanner--grid', 0),
};
